"""Authoritative capture records, lifecycle control, and reusable runners."""

from sifi_streamer.capture.controller import (
    CaptureBackend,
    CaptureController,
    NoCaptureController,
)
from sifi_streamer.capture.records import (
    Attributes,
    CaptureDecodeError,
    CaptureError,
    CaptureLifecycleError,
    CaptureLogReader,
    CaptureLogWriter,
    CaptureRecord,
    CaptureStarted,
    CaptureStopped,
    Marker,
    RawPacket,
    Scalar,
    SegmentStarted,
    SegmentStopped,
    decode_record,
    encode_record,
    record_to_wire_map,
    validate_attributes,
)
from sifi_streamer.capture.runners import (
    interactive_annotations,
    parse_attributes,
    parse_scalar,
    run_capture,
    run_interactive_capture,
    run_timed_capture,
    run_until_interrupt,
)

__all__ = [
    "Attributes",
    "CaptureBackend",
    "CaptureController",
    "CaptureDecodeError",
    "CaptureError",
    "CaptureLifecycleError",
    "CaptureLogReader",
    "CaptureLogWriter",
    "CaptureRecord",
    "CaptureStarted",
    "CaptureStopped",
    "Marker",
    "NoCaptureController",
    "RawPacket",
    "Scalar",
    "SegmentStarted",
    "SegmentStopped",
    "decode_record",
    "encode_record",
    "interactive_annotations",
    "parse_attributes",
    "parse_scalar",
    "record_to_wire_map",
    "run_capture",
    "run_interactive_capture",
    "run_timed_capture",
    "run_until_interrupt",
    "validate_attributes",
]
