"""Public API for reusable SiFi acquisition and authoritative capture logging.

The package exposes three principal layers: device-neutral capture records and
controllers, SiFi-specific live acquisition, and explicit vendor-bridge
installation. Most consumers should import from this module and construct a
controller with :func:`create_sifi_capture`.
"""

from sifi_streamer.annotation_kinds import (
    AnnotationKindDefinition,
    AnnotationKindRegistry,
    AnnotationTarget,
)
from sifi_streamer.bridge import EMG_SAMPLE_RATES, BridgeTransport, SiFiBridgeDevice
from sifi_streamer.bridge_download import (
    TESTED_VERSION,
    BridgeAsset,
    BridgeDownloadError,
    BridgeInstallManifest,
    install_bridge,
    tagged_asset,
)
from sifi_streamer.capture import (
    Attributes,
    CaptureDecodeError,
    CaptureError,
    CaptureLifecycleError,
    CaptureLogReader,
    CaptureLogWriter,
    CaptureRecord,
    CaptureStarted,
    CaptureStopped,
    Marker,
    RawPacket,
    Scalar,
    SegmentStarted,
    SegmentStopped,
    decode_record,
    encode_record,
    record_to_wire_map,
    validate_attributes,
)
from sifi_streamer.client.handle import BackgroundHandle
from sifi_streamer.client.reader import SharedMemoryReader, SignalWindow
from sifi_streamer.config import StreamerConfig
from sifi_streamer.controller import (
    CaptureBackend,
    CaptureController,
    NoCaptureController,
)
from sifi_streamer.devices import (
    DEFAULT_MODALITIES,
    SIGNAL_MODALITIES,
    AcquisitionDevice,
    AcquisitionPacket,
    DeviceFactory,
    Modalities,
    Modality,
    ModalitySpec,
    PacketReader,
    SiFiBandDevice,
    SiFiDevice,
    SiFiPacket,
    SignalChannelSpec,
    SignalStreamSpec,
    SyntheticSiFiDevice,
    modalities_from_device_info,
    packet_from_json_line,
    streams_from_modalities,
)
from sifi_streamer.exceptions import (
    AckError,
    AckTimeoutError,
    CaptureInitializationError,
    DeviceError,
    RecordingError,
    StaleDataError,
    StreamerError,
)
from sifi_streamer.health import (
    HealthEvent,
    HealthSeverity,
    HealthSnapshot,
    HealthThresholds,
    StreamHealth,
)
from sifi_streamer.health_log import HealthLogWriter, default_health_path
from sifi_streamer.monitor import AcquisitionMonitor, CaptureRuntime
from sifi_streamer.protocol import (
    AckMessage,
    AddMarker,
    CommandMessage,
    ErrorAck,
    MarkerAdded,
    ModalityInfo,
    Ready,
    Shutdown,
    StartCapture,
    StartSegment,
    StopCapture,
    StopSegment,
    StreamInfo,
)
from sifi_streamer.runner import (
    interactive_annotations,
    parse_attributes,
    parse_scalar,
    run_capture,
    run_interactive_capture,
    run_timed_capture,
    run_until_interrupt,
)
from sifi_streamer.sifi_backend import (
    AcquisitionCaptureBackend,
    SiFiCaptureBackend,
    create_capture_runtime,
    create_sifi_capture,
    create_sifi_capture_runtime,
)
from sifi_streamer.web import WebCaptureCoordinator, serve_capture_web

__all__ = [
    "DEFAULT_MODALITIES",
    "EMG_SAMPLE_RATES",
    "SIGNAL_MODALITIES",
    "TESTED_VERSION",
    "AckError",
    "AckMessage",
    "AckTimeoutError",
    "AcquisitionCaptureBackend",
    "AcquisitionDevice",
    "AcquisitionMonitor",
    "AcquisitionPacket",
    "AddMarker",
    "AnnotationKindDefinition",
    "AnnotationKindRegistry",
    "AnnotationTarget",
    "Attributes",
    "BackgroundHandle",
    "BridgeAsset",
    "BridgeDownloadError",
    "BridgeInstallManifest",
    "BridgeTransport",
    "CaptureBackend",
    "CaptureController",
    "CaptureDecodeError",
    "CaptureError",
    "CaptureInitializationError",
    "CaptureLifecycleError",
    "CaptureLogReader",
    "CaptureLogWriter",
    "CaptureRecord",
    "CaptureRuntime",
    "CaptureStarted",
    "CaptureStopped",
    "CommandMessage",
    "DeviceError",
    "DeviceFactory",
    "ErrorAck",
    "HealthEvent",
    "HealthLogWriter",
    "HealthSeverity",
    "HealthSnapshot",
    "HealthThresholds",
    "Marker",
    "MarkerAdded",
    "Modalities",
    "Modality",
    "ModalityInfo",
    "ModalitySpec",
    "NoCaptureController",
    "PacketReader",
    "RawPacket",
    "Ready",
    "RecordingError",
    "Scalar",
    "SegmentStarted",
    "SegmentStopped",
    "SharedMemoryReader",
    "Shutdown",
    "SiFiBandDevice",
    "SiFiBridgeDevice",
    "SiFiCaptureBackend",
    "SiFiDevice",
    "SiFiPacket",
    "SignalChannelSpec",
    "SignalStreamSpec",
    "SignalWindow",
    "StaleDataError",
    "StartCapture",
    "StartSegment",
    "StopCapture",
    "StopSegment",
    "StreamHealth",
    "StreamInfo",
    "StreamerConfig",
    "StreamerError",
    "SyntheticSiFiDevice",
    "WebCaptureCoordinator",
    "create_capture_runtime",
    "create_sifi_capture",
    "create_sifi_capture_runtime",
    "decode_record",
    "default_health_path",
    "encode_record",
    "install_bridge",
    "interactive_annotations",
    "modalities_from_device_info",
    "packet_from_json_line",
    "parse_attributes",
    "parse_scalar",
    "record_to_wire_map",
    "run_capture",
    "run_interactive_capture",
    "run_timed_capture",
    "run_until_interrupt",
    "serve_capture_web",
    "streams_from_modalities",
    "tagged_asset",
    "validate_attributes",
]
